# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bddfe8a156d4ef6ff70d86f0c6abeda7a9f607dc2fdde4a84d86acee3e08003dc0f914efc5bb1c383d672bf556835c5031052ee181e6fb9897abb040d5baa1e8
  facebook_app_id: <%= ENV["APP_ID"] %>
  facebook_app_secret: <%= ENV["APP_SECRET"] %>

test:
  secret_key_base: ec16dda18578c13ff89f48ca265e5e496c34f95d289a1b1947b669171db43df52bb789e59ee466618d06b78f61c50021c6e531bd825ec849f35a00a59265ec5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: <%= ENV["APP_ID"] %>
  facebook_app_secret: <%= ENV["APP_SECRET"] %>
